before_script:
  - psql -c 'create database test_reregretsy_database;' -U postgres
  - psql -d test_reregretsy_database -c 'CREATE TABLE products (id text unique, product_name text, product_price real, img_url text, seller_name text,seller_username text, seller_avatar text);' -U postgres
sudo: true
language: node_js
node_js:
  - "stable"
services:
  - postgresql
script:
  - ./database/tests/init-db.sh
  - npm run test
notifications:
  email: false
