before_script:
  - psql -c 'create database test_reregretsy_database;' -U postgres
sudo: false
language: node_js
node_js:
  - "stable"
services:
  - postgresql
script: npm run test
notifications:
  email: false